kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: smartvillage-platform
  namespace: smart-village-view
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: 'quay.io/computateorg/smartvillage-platform:latest'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
