apiVersion: redhatcop.redhat.io/v1alpha1
kind: Policy
metadata:
  name: vault-secret-reader
  namespace: vault-admin
spec:
  # Add fields here
  authentication: 
    path: kubernetes
    role: policy-admin
  connection:
    address: 'http://vault.vault.svc.cluster.local:8200'
  policy: |
    path "/test/data/*" {
      capabilities = ["read"]
    }
