apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: betydb
  namespace: pecan
spec:
  data:
    - match:
        remoteRef:
          remoteKey: betydb
        secretKey: stuff
  deletionPolicy: None
  secretStoreRefs:
    - kind: SecretStore
      name: secret-store
  selector:
    secret:
      name: betydb
