apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: iotagent-ul
  namespace: fiware
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: iotagent-ul:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/telefonicaid/iotagent-ul.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: nodejs:16-ubi8
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - generic:
      secretReference:
        name: iotagent-ul-generic-webhook-secret
    type: Generic
  - github:
      secretReference:
        name: iotagent-ul-github-webhook-secret
    type: GitHub
  - imageChange: {}
    type: ImageChange
  - type: ConfigChange
