kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: pecan
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
allowHostNetwork: true
allowPrivilegeEscalation: true
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostPID: false
allowHostPorts: false
allowPrivilegedContainer: false
readOnlyRootFilesystem: false
users:
- system:serviceaccount:pecan:pecan-helm-rabbitmq
