kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: fiware-broker-hdls-svc
spec:
  host: fiware-broker-hdls-svc-fiware.apps-crc.testing
  to:
    kind: Service
    name: fiware-broker-hdls-svc
    weight: 100
  port:
    targetPort: all
  wildcardPolicy: None
