apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-db-secret
  namespace: sso
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  target:
    name: keycloak-db-secret
    template:
      type: Opaque
      engineVersion: v2
      data:
        POSTGRES_DATABASE: "sso"
        POSTGRES_EXTERNAL_ADDRESS: "postgres-cluster-ha.postgres.svc.cluster.local"
        POSTGRES_EXTERNAL_PORT: "5432"
        POSTGRES_HOST: "postgres-cluster-ha.postgres.svc.cluster.local"
        POSTGRES_PASSWORD: "{{ .POSTGRES_PASSWORD }}"
        POSTGRES_SUPERUSER: "true"
        POSTGRES_USERNAME: "sso"
  data:
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: sso/kv/keycloak-db-secret
      property: POSTGRES_PASSWORD
