apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: betydb
  namespace: pecan
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  target:
    name: betydb
    template:
      type: Opaque
      engineVersion: v2
      data:
        betyPassword: "{{ .betyPassword }}"
        postgresqlPassword: "{{ .postgresqlPassword }}"
        secretKey: "{{ .secretKey }}"
  data:
  - secretKey: betyPassword
    remoteRef:
      key: pecan/kv/betydb
      property: betyPassword
  - secretKey: postgresqlPassword
    remoteRef:
      key: pecan/kv/betydb
      property: postgresqlPassword
  - secretKey: secretKey
    remoteRef:
      key: pecan/kv/betydb-secret-key
      property: secretKey
