apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: smartabyar-data-science-notebook
  namespace: redhat-ods-applications
  labels:
    opendatahub.io/notebook-image: "true"
  annotations:
    opendatahub.io/notebook-image-url: "https://github.com/computate-org/smartabyar-data-science-notebook"
    opendatahub.io/notebook-image-name: "Smarta Byar Smart Village Data Science Notebook with SUMO"
    opendatahub.io/notebook-image-desc: "Smarta Byar Smart Village Data Science Notebook with SUMO."
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      annotations: null
      from:
        kind: DockerImage
        name: 'quay.io/computateorg/smartabyar-data-science-notebook:latest'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
