---
- name: Fetch the database SSO secrets
  set_fact:
    SSO_POSTGRES_SECRET: "{{ query('kubernetes.core.k8s', kind='Secret', resource_name=SSO_POSTGRES_SECRET_NAME, namespace=SSO_NAMESPACE, validate_certs=false)[0].data }}"
  vars:
    K8S_AUTH_HOST: "{{ REDHAT_OPENSHIFT_HOST }}"
    K8S_AUTH_API_KEY: "{{ REDHAT_OPENSHIFT_TOKEN }}"
  register: fetch_database_sso_secrets
  ignore_errors: true
- fail:
    msg: >
      Missing variables REDHAT_OPENSHIFT_HOST and REDHAT_OPENSHIFT_TOKEN. 
      Find the login command to OpenShift and and set these variables, for example: 
      ansible-playbook ~/.local/src/smartabyar-smartvillage/openshift/ansible/sso-configure-database.yml
      -e REDHAT_OPENSHIFT_HOST=https://api.crc.testing:6443
      -e REDHAT_OPENSHIFT_TOKEN=sha256~KNsu4uF9jsFUVZJE6smixzmWhoHVq9rgADUICQIrrDI
  when: fetch_database_sso_secrets.failed
- name: Update postgres sso password from vault
  kubernetes.core.k8s_json_patch:
    namespace: "{{ POSTGRES_NAMESPACE }}"
    kind: Secret
    name: "{{ POSTGRES_USER_SECRET_SSO }}"
    host: "{{ REDHAT_OPENSHIFT_HOST }}"
    api_key: "{{ REDHAT_OPENSHIFT_TOKEN }}"
    validate_certs: false
    patch:
      - op: replace
        path: /data/password
        value: "{{ SSO_POSTGRES_SECRET.POSTGRES_PASSWORD }}"
      - op: replace
        path: /data/verifier
        value: ""
  ignore_errors: true
- name: Delete keycloak pods
  kubernetes.core.k8s:
    namespace: "{{ SSO_NAMESPACE }}"
    kind: Pod
    state: absent
    name: "keycloak-0"
    host: "{{ REDHAT_OPENSHIFT_HOST }}"
    api_key: "{{ REDHAT_OPENSHIFT_TOKEN }}"
    validate_certs: false
