---
- name: Get SSO admin password
  set_fact:
    SSO_ADMIN_PASSWORD: "{{ query('kubernetes.core.k8s', kind='Secret', resource_name='credential-sso', namespace=SSO_NAMESPACE, validate_certs=false)[0].data.ADMIN_PASSWORD | b64decode }}"
  vars:
    K8S_AUTH_HOST: "{{ REDHAT_OPENSHIFT_HOST }}"
    K8S_AUTH_API_KEY: "{{ REDHAT_OPENSHIFT_TOKEN }}"
  register: GET_SSO_ADMIN_PASSWORD
- fail:
    msg: >
      Missing variables REDHAT_OPENSHIFT_HOST and REDHAT_OPENSHIFT_TOKEN. 
      Find the login command to OpenShift and and set these variables, for example: 
      ansible-playbook ~/.local/src/smartabyar-smartvillage/openshift/ansible/sso-configure-database.yml
      -e REDHAT_OPENSHIFT_HOST=https://api.crc.testing:6443
      -e REDHAT_OPENSHIFT_TOKEN=sha256~KNsu4uF9jsFUVZJE6smixzmWhoHVq9rgADUICQIrrDI
  when: GET_SSO_ADMIN_PASSWORD.failed
- name: "Create Token for SSO"
  uri:
    validate_certs: false
    url: "{{ SSO_SITE_BASE_URL }}/auth/realms/master/protocol/openid-connect/token"
    method: POST
    body_format: form-urlencoded
    body:
      username: "{{ SSO_ADMIN_USERNAME }}"
      password: "{{ SSO_ADMIN_PASSWORD }}"
      grant_type: "password"
      client_id: "admin-cli"
  register: SSO_TOKEN
- name: "Update SSO Master Realm for longer token timeout"
  uri:
    validate_certs: false
    url: "{{ SSO_SITE_BASE_URL }}/auth/admin/realms/master"
    method: PUT
    body_format: json
    body: "{{ lookup('template', 'sso-master-realm-extend-token.json') }}"
    status_code:
      - 204
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
      Authorization: "Bearer {{ SSO_TOKEN.json.access_token }}"
