apiVersion: solr.apache.org/v1beta1
kind: SolrCloud
metadata:
  name: default
  namespace: solr
spec:
  replicas: 2
  solrImage:
    tag: 8.1.1
  dataStorage:
    persistent:
      pvcTemplate:
        spec:
          resources:
            requests:
              storage: 20Gi
  customSolrKubeOptions:
    podOptions:
      podSecurityContext:
        runAsUser: 1001
      serviceAccountName: solr
