---
apiVersion: solr.apache.org/v1beta1
kind: SolrCloud
metadata:
  name: site-solrcloud
  namespace: solr
spec:
  solrLogLevel: INFO
  busyBoxImage:
    repository: library/busybox
    tag: 1.28.0-glibc
  solrJavaMem: '-Xms1g -Xmx2g'
  dataStorage: {}
  solrAddressability:
    commonServicePort: 80
    podPort: 8983
  solrImage:
    repository: library/solr
    tag: 8.1.1
  replicas: 0
  updateStrategy:
    managed: {}
    method: Managed
  customSolrKubeOptions: {}
