apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - securitycontextconstraints/
  - randomsecrets/
  - secretstores/
  - secretenginemounts/
  - externalsecrets/
  - postgresclusters/
