apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: smartvillage
  namespace: sso
  labels:
    app: sso
    realm: SMARTVILLAGE
spec:
  realm:
    id: "SMARTVILLAGE"
    realm: "SMARTVILLAGE"
    enabled: True
    displayName: "SMARTVILLAGE"
    clientScopes:
      - id: smartvillage
        name: smartvillage
        description: A client scope for the smartvillage client
        protocol: openid-connect
#        protocolMappers:
#          - id: smartvillage
#            name: smartvillage
#            protocol: openid-connect
#
#            mapperType: Audience
#            includedClientAudience: smartvillage
#            addToAccessToken: true
  instanceSelector:
    matchLabels:
      app: sso