apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-orion
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/FIWARE-Ops/marinera.git
    targetRevision: HEAD
    path: applications/mongodb/chart
  destination:
    namespace: fiware
    server: 'https://kubernetes.default.svc'
    helm:
      parameters:
        - name: mongodb.architecture
          value: standalone
  syncPolicy:
    automated:
      # resources that no longer exist get deleted on sync
      prune: true
      # sync will be attempted again on failure after self heal timeout (5 seconds by default)
      selfHeal: true
