---

API_VERSION: 2.0.3
SITE_NAME: smartvillage-platform
SITE_DISPLAY_NAME: Smart Village Platform
SITE_PUBLIC_URL: https://smartabyarsmartvillage.org
MAILING_LIST_URL: https://computate.topicbox.com/groups/smartvillage-platform
SITE_HOST_NAME: localhost
SITE_PORT: 12080
SITE_BASE_URL: "http://localhost:12080"
SITE_ZONE: America/New_York
SITE_LOCALE: en-US
SITE_INSTANCES: 5
WORKER_POOL_SIZE: 2
VERTX_MAX_EVENT_LOOP_EXECUTE_TIME: 30
VERTX_MAX_WORKER_EXECUTE_TIME: 6000
VERTX_WARNING_EXCEPTION_SECONDS: 60
CLUSTER_HOST_NAME: localhost
CLUSTER_PORT: 12081
FACEBOOK_GRAPH_VERSION: v15.0
FACEBOOK_APP_ID: 1871568493111919
GITHUB_ORG: "computate-org"
QUAYIO_ORG: "computateorg"
SITE_POWERED_BY_URL: "https://nerc.mghpcc.org/"
SITE_POWERED_BY_NAME: "NERC"
SITE_POWERED_BY_IMAGE_URI: "/png/nerc/nerc-logo.png"
ENABLE_ZOOKEEPER_CLUSTER: true
ENABLE_KAFKA: true

STATIC_BASE_URL: "http://localhost:12080/static"
STATIC_PATH: "/usr/local/src/smartvillage-platform-static"

API_CONTACT_EMAIL: 
API_COUNTER_RESUME: 0
API_COUNTER_FETCH: 10
API_COUNTER_FETCH_SitePage: 10
API_COUNTER_FETCH_SiteHtm: 10

JDBC_HOST: localhost
JDBC_PORT: 5432
JDBC_DATABASE: smartvillage
JDBC_USERNAME: smartvillage
JDBC_PASSWORD: password
JDBC_MAX_POOL_SIZE: 10
JDBC_MAX_WAIT_QUEUE_SIZE: 1000

AUTH_REALM: 
AUTH_CLIENT: 
AUTH_SECRET: 
AUTH_HOST_NAME: 
AUTH_PORT: 443
AUTH_SSL: true
AUTH_SSL_REQUIRED: all
AUTH_TOKEN_URI: /auth/realms/AUTH_REALM/protocol/openid-connect/token
AUTH_FINE_GRAINED_POLICY_PERMISSIONS: false
SSL_VERIFY: true

ZOOKEEPER_HOST_NAME: localhost
ZOOKEEPER_PORT: 2181
ZOOKEEPER_RETRY_POLICY: one_time
ZOOKEEPER_BASE_SLEEP_TIME_MILLIS: 5000
ZOOKEEPER_MAX_SLEEP_MILLIS: 5000
ZOOKEEPER_MAX_RETRIES: 5
ZOOKEEPER_CONNECTION_TIMEOUT_MILLIS: 3000
ZOOKEEPER_SESSION_TIMEOUT_MILLIS: 5000

SOLR_URL: https://solr-solr.apps-crc.testing/solr/smartvillage
SOLR_HOST_NAME: solr-smartvillage.apps-crc.testing
SOLR_PORT: 443
SOLR_COLLECTION: smartvillage
SOLR_SSL: True
SOLR_HOST_NAME_COMPUTATE: solr-smartvillage.apps-crc.testing
SOLR_PORT_COMPUTATE: 443
SOLR_COLLECTION_COMPUTATE: computate
SOLR_SSL_COMPUTATE: True
SOLR_URL_COMPUTATE: "https://solr-solr.apps-crc.testing/solr/computate"
SOLR_WORKER_COMMIT_WITHIN_MILLIS: 10000

EMAIL_HOST: 
EMAIL_PORT: 
EMAIL_SSL: 
EMAIL_AUTH: 
EMAIL_USERNAME: 
EMAIL_PASSWORD: 
EMAIL_FROM: 
EMAIL_ADMIN: 

OPEN_TELEMETRY_ENABLED: false

REFRESH_DATA_PAUSE_IN_SECONDS: 10
ENABLE_REFRESH_DATA: false
ENABLE_REFRESH_DATA_SiteHtm: true
ENABLE_REFRESH_DATA_SitePage: true
ENABLE_REFRESH_DATA_SystemEvent: true
ENABLE_REFRESH_DATA_MapResult: true

ENABLE_IMPORT_DATA: true
ENABLE_IMPORT_DATA_SiteHtm: true
ENABLE_IMPORT_DATA_SitePage: true
ENABLE_IMPORT_DATA_SystemEvent: true
ENABLE_IMPORT_DATA_MapResult: true

# The Auth roles required to be an admin in the site. 
AUTH_ROLE_ADMIN: 'SiteAdmin'
# The Auth roles required to add and modify site user records. 
AUTH_ROLE_REQUIRED_SiteUser: 'SiteAdmin'
# The Auth roles required to add and modify HTML records. 
AUTH_ROLE_REQUIRED_SiteHtm: 'SiteAdmin'
# The Auth roles required to add and modify article records. 
AUTH_ROLE_REQUIRED_SitePage: 'SiteAdmin'
# The Auth roles required to add and modify system event records. 
AUTH_ROLE_REQUIRED_SystemEvent: 'SiteAdmin'
# The Auth roles required to add and modify map result records. 
AUTH_ROLE_REQUIRED_MapResult: 'SiteAdmin'
