kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: iotagent-json-north
spec:
  to:
    kind: Service
    name: iotagent-json
    weight: 100
  port:
    targetPort: 4041-north-port
  wildcardPolicy: None
