---
REDHAT_OPENSHIFT_HOST: https://api.crc.testing:6443
REDHAT_OPENSHIFT_TOKEN: "{{ lookup('env', 'REDHAT_OPENSHIFT_TOKEN') | default(omit) }}"
SSO_SITE_BASE_URL: https://keycloak-sso.apps-crc.testing
SSO_ADMIN_USERNAME: admin
SSO_NAMESPACE: sso
SSO_SMARTVILLAGE_REALM_NAME: SMARTVILLAGE
SSO_SMARTVILLAGE_CLIENT_NAME: smartvillage

SSO_AUTHORIZATION_RESOURCES:
  - name: TrafficSimulation
    displayName: TrafficSimulation
    uris:
      - /api/traffic-simulation
      - /traffic-simulation
    scopes:
      - POST
      - DELETE
      - GET
      - PATCH
      - PUTImport
      - Search
  - name: SiteUser
    displayName: SiteUser
    uris:
      - /api/user
      - /user
    scopes:
      - POST
      - DELETE
      - GET
      - PATCH
      - PUTImport
      - Search
