---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: smart-village-view
  namespace: smart-village-view
spec:
  strategy:
    type: Recreate
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - smart-village-view
        from:
          kind: ImageStreamTag
          namespace: smart-village-view
          name: 'smart-village-view:latest'
    - type: ConfigChange
  replicas: 3
  revisionHistoryLimit: 10
  test: false
  selector:
    app: smart-village-view
    deploymentconfig: smart-village-view
  template:
    metadata:
      labels:
        app: smart-village-view
        deploymentconfig: smart-village-view
    spec:
      containers:
        - name: osmWebWizard
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: Always
          terminationMessagePolicy: File
          resources:
            limits:
              cpu: 250m
              memory: 1000Mi
            requests:
              cpu: 250m
              memory: 1000Mi
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 20
          terminationMessagePath: /dev/termination-log
          command:
            - --address 0.0.0.0
            - --port 8010
            - -o OUTPUTDIR
            - --nooutput
          ports:
            - name: websocket
              containerPort: 8010
              protocol: TCP
        - name: smart-village-view
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: Always
          terminationMessagePolicy: File
          resources:
            limits:
              cpu: 250m
              memory: 1000Mi
            requests:
              cpu: 250m
              memory: 1000Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 20
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 20
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: cluster
              containerPort: 8081
              protocol: TCP
            - name: prometheus
              containerPort: 9779
              protocol: TCP
            - name: jolokia
              containerPort: 8778
              protocol: TCP
            - name: jms
              containerPort: 3333
              protocol: TCP
            - name: debug
              containerPort: 8998
              protocol: TCP
          env:
            - name: AUTH_REALM
              valueFrom:
                secretKeyRef:
                  name: smart-village-view-secret
                  key: AUTH_REALM
            - name: AUTH_CLIENT
              valueFrom:
                secretKeyRef:
                  name: smart-village-view-secret
                  key: AUTH_CLIENT
            - name: AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: smart-village-view-secret
                  key: AUTH_SECRET
            - name: AUTH_HOST_NAME
              valueFrom:
                secretKeyRef:
                  name: smart-village-view-secret
                  key: AUTH_HOST_NAME
            - name: AUTH_PORT
              valueFrom:
                secretKeyRef:
                  name: smart-village-view-secret
                  key: AUTH_PORT
            - name: AUTH_SSL
              valueFrom:
                secretKeyRef:
                  name: smart-village-view-secret
                  key: AUTH_SSL
            - name: AUTH_URL
              valueFrom:
                secretKeyRef:
                  name: smart-village-view-secret
                  key: AUTH_URL
            - name: AUTH_TOKEN_URI
              value: /auth/realms/RH-IMPACT/protocol/openid-connect/token
            - name: EMAIL_AUTH
              valueFrom:
                secretKeyRef:
                  name: smart-village-view-secret
                  key: EMAIL_AUTH
            - name: EMAIL_FROM
              valueFrom:
                secretKeyRef:
                  name: smart-village-view-secret
                  key: EMAIL_FROM
            - name: EMAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: smart-village-view-secret
                  key: EMAIL_HOST
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smart-village-view-secret
                  key: EMAIL_PASSWORD
            - name: EMAIL_PORT
              valueFrom:
                secretKeyRef:
                  name: smart-village-view-secret
                  key: EMAIL_PORT
            - name: EMAIL_SSL
              valueFrom:
                secretKeyRef:
                  name: smart-village-view-secret
                  key: EMAIL_SSL
            - name: EMAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: smart-village-view-secret
                  key: EMAIL_USERNAME
            - name: JDBC_HOST
              valueFrom:
                secretKeyRef:
                  name: smart-village-view-secret
                  key: JDBC_HOST
            - name: JDBC_PORT
              valueFrom:
                secretKeyRef:
                  name: smart-village-view-secret
                  key: JDBC_PORT
            - name: JDBC_DATABASE
              valueFrom:
                secretKeyRef:
                  name: smart-village-view-secret
                  key: JDBC_DATABASE
            - name: JDBC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: smart-village-view-secret
                  key: JDBC_USERNAME
            - name: JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smart-village-view-secret
                  key: JDBC_PASSWORD
            - name: OPENSHIFT_SERVICE
              value: smart-village-view
            - name: CLUSTER_PORT
              value: '8081'
            - name: ZOOKEEPER_HOST_NAME
              value: zookeeper.smart-village-view.svc
            - name: ZOOKEEPER_PORT
              value: '2181'
            - name: SOLR_HOST_NAME
              value: solr.smart-village-view.svc
            - name: SOLR_PORT
              value: '8983'
            - name: SOLR_URL
              value: 'http://solr.smart-village-view.svc:8983/solr/smart-village-view'
            - name: SOLR_COLLECTION
              value: smart-village-view
            - name: SITE_HOST_NAME
              value: smartvillage.computate.org
            - name: SITE_PORT
              value: '8080'
            - name: SITE_BASE_URL
              value: 'https://smartvillage.computate.org'
            - name: STATIC_BASE_URL
              value: 'https://computate.neocities.org/smart-village-view'
            - name: STATIC_PATH
              value: /root/src/src/main/resources/webroot
            - name: SITE_ZONE
              value: America/Denver
            - name: SITE_LOCALE
              value: en-US
            - name: JAVA_MAIN_CLASS
              value: org.curriki.api.enus.vertx.MainVerticle
            - name: SITE_INSTANCES
              value: '2'
            - name: WORKER_POOL_SIZE
              value: '2'
            - name: ENABLE_IMPORT_DATA
              value: 'false'
            - name: AUTH_ROLE_ADMIN
              value: '"SiteAdmin"'
            - name: AUTH_ROLE_REQUIRED_SiteUser
              value: '"SiteAdmin"'
            - name: AUTH_ROLE_REQUIRED_IotNode
              value: '"SiteAdmin"'
            - name: YGGIO_HOST_NAME
              valueFrom:
                secretKeyRef:
                  name: smart-village-view-secret
                  key: YGGIO_HOST_NAME
            - name: YGGIO_PORT
              valueFrom:
                secretKeyRef:
                  name: smart-village-view-secret
                  key: YGGIO_PORT
            - name: YGGIO_SSL
              valueFrom:
                secretKeyRef:
                  name: smart-village-view-secret
                  key: YGGIO_SSL
            - name: YGGIO_API_RELATIVE_URI
              valueFrom:
                secretKeyRef:
                  name: smart-village-view-secret
                  key: YGGIO_API_RELATIVE_URI
            - name: YGGIO_AUTH_TOKEN_URI
              valueFrom:
                secretKeyRef:
                  name: smart-village-view-secret
                  key: YGGIO_AUTH_TOKEN_URI
            - name: YGGIO_AUTH_LOCAL_URI
              valueFrom:
                secretKeyRef:
                  name: smart-village-view-secret
                  key: YGGIO_AUTH_LOCAL_URI
            - name: YGGIO_AUTH_SCOPE
              valueFrom:
                secretKeyRef:
                  name: smart-village-view-secret
                  key: YGGIO_AUTH_SCOPE
            - name: YGGIO_AUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: smart-village-view-secret
                  key: YGGIO_AUTH_CLIENT_ID
            - name: YGGIO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: smart-village-view-secret
                  key: YGGIO_USERNAME
            - name: YGGIO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smart-village-view-secret
                  key: YGGIO_PASSWORD
            - name: YGGIO_API_RELATIVE_URI_IotNode
              value: /api/iotnodes
            - name: FONTAWESOME_KIT
              valueFrom:
                secretKeyRef:
                  name: smart-village-view-secret
                  key: FONTAWESOME_KIT
            - name: ENABLE_REFRESH_DATA
              value: 'false'
            - name: DYNAMIC_PAGE_PATH
              value: /root/src/src/main/resources/page
            - name: ENABLE_ZOOKEEPER_CLUSTER
              value: 'true'
            - name: CLUSTER_HOST_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: VERTX_WARNING_EXCEPTION_SECONDS
              value: '60'
            - name: CLUSTER_PUBLIC_HOST_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: TEMPLATE_PATH
              value: /root/src/src/main/resources/templates
            - name: JAVA_OPTS
            - name: FCD_SYNC_PATH
              value: /usr/local/share/sumo/fcd
            - name: DEFAULT_MAP_LOCATION
              value: '55.61888,13.548799'
            - name: DEFAULT_MAP_ZOOM
              value: '11'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
