apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zookeeper
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/computate-org/smartabyar-smartvillage.git
    targetRevision: HEAD
    path: openshift/kustomize/bundles/zookeeper/app
  destination:
    namespace: zookeeper
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      # resources that no longer exist get deleted on sync
      prune: true
      # sync will be attempted again on failure after self heal timeout (5 seconds by default)
      selfHeal: true
