kind: KafkaTopic
apiVersion: kafka.strimzi.io/v1beta2
metadata:
  name: fiware-topic
  labels:
    strimzi.io/cluster: fiware-kafka
  namespace: fiware
spec:
  partitions: 10
  replicas: 3
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
