kind: Service
apiVersion: v1
metadata:
  name: kafka
  namespace: smart-village-view
spec:
  ports:
    - name: kafka
      protocol: TCP
      port: 9092
      targetPort: 9092
      nodePort: 30092
  type: NodePort
  selector:
    strimzi.io/kind: Kafka
    strimzi.io/cluster: smartvillage-kafka
    strimzi.io/name: smartvillage-kafka-kafka
