apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongodb-secret
  namespace: fiware
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  target:
    name: mongodb-secret
    template:
      type: Opaque
      engineVersion: v2
      data:
        mongodb-password: "{{ .mongodb-password }}"
        mongodb-replica-set-key: "{{ .mongodb-replica-set-key }}"
        mongodb-root-password: "{{ .mongodb-root-password }}"
  data:
  - secretKey: mongodb-password
    remoteRef:
      key: fiware/kv/mongodb-password
      property: mongodb-password
  - secretKey: mongodb-replica-set-key
    remoteRef:
      key: fiware/kv/mongodb-replica-set-key
      property: mongodb-replica-set-key
  - secretKey: mongodb-root-password
    remoteRef:
      key: fiware/kv/mongodb-root-password
      property: mongodb-root-password
