apiVersion: smartvillage.computate.org/v1
kind: TrafficFlowObserved
metadata:
  name: sweden-veberod-1-sjobovagen-se
  namespace: smart-village-faeeb6c
spec:
  description: |
    An observation of traffic flow conditions at a certain place and time.
  attributes:
    address:
      addressCountry: Sweden
      addressLocality: Veberöd
      streetAddress: Sjöbovägen
    area_served: |
      96027913#0 96027913#2 30186293 311389510#1
    average_gap_distance: 1
  iotagent:
    base_url: http://iotagent-json-smartvillage.apps-crc.testing
  context_broker:
    base_url: http://orion-ld-smartvillage.apps-crc.testing
  fiware:
    service: |-
      smarttrafficlights
    service_path: |-
      /Sweden/Veberod/CityCenter
  service_group:
    resource: |-
      /iot/json
    apikey: |-
      VeberodIntersection1
  device:
    transport: |-
      MQTT
    id: |-
      Sjobovagen-SE
    mqtt_host: |-
      fiware-broker-mqtt-0-svc
    mqtt_port: 1883
    mqtt_subscription_topic: |-
      iot/subscribe
    subscription_url: |-
      http://orionld-smartvillage-sync:8080
  smartabyar_smartvillage:
    enabled: True
    auth_token_url: https://sso.computate.org/auth/realms/SMARTVILLAGE/protocol/openid-connect/token
    site_base_url: https://www.smartabyarsmartvillage.org
  alternate_model:
    enabled: True
    id: |-
      sumo
    name: |-
      SUMO
