apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: iotagent-json
  namespace: fiware
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: iotagent-json:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/telefonicaid/iotagent-json.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: nodejs:16-ubi8
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - generic:
      secretReference:
        name: iotagent-json-generic-webhook-secret
    type: Generic
  - github:
      secretReference:
        name: iotagent-json-github-webhook-secret
    type: GitHub
  - imageChange: {}
    type: ImageChange
  - type: ConfigChange
