apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
    - name: developer
      type: HTPasswd
      mappingMethod: claim
      htpasswd:
        fileData:
          name: htpass-secret
    - name: sso
      mappingMethod: claim
      type: OpenID
      openID:
        clientID: smartvillage
        clientSecret:
          name: sso-openshift-client-secret
        ca:
          # Create with this command: 
          # oc -n openshift-config create configmap sso-ca-config-map --from-literal="ca.crt=$(oc -n openshift-ingress-operator get secret/router-ca -o jsonpath='{.data.tls\.crt}' | base64 -d)"
          name: sso-ca-config-map
        claims: 
          preferredUsername:
            - preferred_username
            - username
          name:
            - name
            - full name
          email:
            - email
          groups:
            - groups
        issuer: https://keycloak-sso.apps-crc.testing/auth/realms/SMARTVILLAGE
