apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: smartvillage-platform
  namespace: smart-village-view
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  target:
    name: smartvillage-platform
    template:
      type: Opaque
      engineVersion: v2
      data:
        JDBC_USERNAME: "{{ .JDBC_USERNAME }}"
        JDBC_PASSWORD: "{{ .JDBC_PASSWORD }}"
        JDBC_DATABASE: "{{ .JDBC_DATABASE }}"
        JDBC_HOST: "{{ .JDBC_HOST }}"
        JDBC_PORT: "{{ .JDBC_PORT }}"
        AUTH_CLIENT: "{{ .AUTH_CLIENT }}"
        AUTH_SECRET: "{{ .AUTH_SECRET }}"
        EMAIL_HOST: "{{ .EMAIL_HOST }}"
        EMAIL_PORT: "{{ .EMAIL_PORT }}"
        EMAIL_FROM: "{{ .EMAIL_FROM }}"
        EMAIL_SSL: "{{ .EMAIL_SSL }}"
        EMAIL_AUTH: "{{ .EMAIL_AUTH }}"
        EMAIL_USERNAME: "{{ .EMAIL_USER }}"
        EMAIL_PASSWORD: "{{ .EMAIL_PASSWORD }}"
        FONTAWESOME_KIT: "{{ .FONTAWESOME_KIT }}"

        YGGIO_HOST_NAME: "{{ .YGGIO_HOST_NAME }}"
        YGGIO_PORT: "{{ .YGGIO_PORT }}"
        YGGIO_SSL: "{{ .YGGIO_SSL }}"
        YGGIO_API_RELATIVE_URI_IotNode: "{{ .YGGIO_API_RELATIVE_URI_IotNode }}"
        YGGIO_AUTH_LOCAL_URI: "{{ .YGGIO_AUTH_LOCAL_URI }}"
        YGGIO_USERNAME: "{{ .YGGIO_USERNAME }}"
        YGGIO_PASSWORD: "{{ .YGGIO_PASSWORD }}"

  data:

  - secretKey: JDBC_USERNAME
    remoteRef:
      key: smart-village-view/kv/postgres-cluster-pguser-smartvillage
      property: user
  - secretKey: JDBC_PASSWORD
    remoteRef:
      key: smart-village-view/kv/postgres-cluster-pguser-smartvillage
      property: password
  - secretKey: JDBC_DATABASE
    remoteRef:
      key: smart-village-view/kv/postgres-cluster-pguser-smartvillage
      property: dbname
  - secretKey: JDBC_HOST
    remoteRef:
      key: smart-village-view/kv/postgres-cluster-pguser-smartvillage
      property: host
  - secretKey: JDBC_PORT
    remoteRef:
      key: smart-village-view/kv/postgres-cluster-pguser-smartvillage
      property: port

  - secretKey: AUTH_CLIENT
    remoteRef:
      key: smart-village-view/kv/keycloak-client-secret-smartvillage
      property: CLIENT_ID
  - secretKey: AUTH_SECRET
    remoteRef:
      key: smart-village-view/kv/keycloak-client-secret-smartvillage
      property: CLIENT_SECRET

  - secretKey: EMAIL_HOST
    remoteRef:
      key: smart-village-view/kv/email
      property: EMAIL_HOST
  - secretKey: EMAIL_PORT
    remoteRef:
      key: smart-village-view/kv/email
      property: EMAIL_PORT
  - secretKey: EMAIL_FROM
    remoteRef:
      key: smart-village-view/kv/email
      property: EMAIL_FROM
  - secretKey: EMAIL_SSL
    remoteRef:
      key: smart-village-view/kv/email
      property: EMAIL_SSL
  - secretKey: EMAIL_AUTH
    remoteRef:
      key: smart-village-view/kv/email
      property: EMAIL_AUTH
  - secretKey: EMAIL_USERNAME
    remoteRef:
      key: smart-village-view/kv/email
      property: EMAIL_USERNAME
  - secretKey: EMAIL_PASSWORD
    remoteRef:
      key: smart-village-view/kv/email
      property: EMAIL_PASSWORD

  - secretKey: FONTAWESOME_KIT
    remoteRef:
      key: smart-village-view/kv/fontawesome
      property: FONTAWESOME_KIT

  - secretKey: YGGIO_HOST_NAME
    remoteRef:
      key: smart-village-view/kv/yggio
      property: YGGIO_HOST_NAME
  - secretKey: YGGIO_PORT
    remoteRef:
      key: smart-village-view/kv/yggio
      property: YGGIO_PORT
  - secretKey: YGGIO_SSL
    remoteRef:
      key: smart-village-view/kv/yggio
      property: YGGIO_SSL
  - secretKey: YGGIO_API_RELATIVE_URI_IotNode
    remoteRef:
      key: smart-village-view/kv/yggio
      property: YGGIO_API_RELATIVE_URI_IotNode
  - secretKey: YGGIO_AUTH_LOCAL_URI
    remoteRef:
      key: smart-village-view/kv/yggio
      property: YGGIO_AUTH_LOCAL_URI
  - secretKey: YGGIO_USERNAME
    remoteRef:
      key: smart-village-view/kv/yggio
      property: YGGIO_USERNAME
  - secretKey: YGGIO_PASSWORD
    remoteRef:
      key: smart-village-view/kv/yggio
      property: YGGIO_PASSWORD
