apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amq-broker
  namespace: fiware
spec:
  project: default
  source:
    repoURL: github.com/computate-org/smartabyar-smartvillage.git
    targetRevision: HEAD
    path: openshift/kustomize/bundles/amq-broker-rhel8/app
  destination:
    name: in-cluster
    namespace: fiware
  syncPolicy:
    automated:
      # resources that no longer exist get deleted on sync
      prune: true
      # sync will be attempted again on failure after self heal timeout (5 seconds by default)
      selfHeal: true
