---
- name: Update secret value to vault
  include_role:
    name: vault-patch-secret
  vars:
    SOURCE_NAMESPACE: postgres
    SOURCE_SECRET_NAME: postgres-cluster-pguser-sso
    SOURCE_SECRET_KEY: password
    DESTINATION_NAMESPACE: sso
    COPY_KEYS:
      - dbname
      - host
      - port
      - user
      - jdbc-uri
    DESTINATION_SECRET_NAME: keycloak-db-secret
    DESTINATION_SECRET_KEY: POSTGRES_PASSWORD

- name: Restart sso pod
  k8s:
    state: absent
    kind: Pod
    name: "keycloak-0"
    host: "{{ REDHAT_OPENSHIFT_HOST }}"
    api_key: "{{ REDHAT_OPENSHIFT_TOKEN }}"
    namespace: "{{ SSO_NAMESPACE }}"
    validate_certs: false
