apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/rolebindings/
  - ../../../../base/applications/postgresql-helm/
patchesStrategicMerge:
  - application.yaml
