kind: Service
apiVersion: v1
metadata:
  name: fiware-broker-mqtt-nodeport
  namespace: fiware
spec:
  ports:
    - name: fiware-broker-mqtt
      protocol: TCP
      port: 1883
      targetPort: 1883
      nodePort: 30083
  type: NodePort
  selector:
    ActiveMQArtemis: fiware-broker
    application: fiware-broker-app
