apiVersion: redhatcop.redhat.io/v1alpha1
kind: RandomSecret
metadata:
  name: keycloak-client-secret-smartvillage
  namespace: smart-village-view
spec:
  authentication: 
    path: kubernetes
    role: secret-writer
  connection:
    address: 'http://vault.vault.svc.cluster.local:8200'
  path: smart-village-view/kv
  secretKey: CLIENT_SECRET
  secretFormat:
    passwordPolicyName: special-characters-password-policy-15
