---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'system:openshift:scc:anyuid'
  namespace: vault
subjects:
  - kind: ServiceAccount
    name: vault
    namespace: vault
  - kind: ServiceAccount
    name: vault-agent-injector
    namespace: vault
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:anyuid'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'system:openshift:scc:privileged'
  namespace: vault
subjects:
  - kind: ServiceAccount
    name: vault
    namespace: vault
  - kind: ServiceAccount
    name: vault-agent-injector
    namespace: vault
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:privileged'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'system:openshift:scc:nonroot'
  namespace: vault
subjects:
  - kind: ServiceAccount
    name: vault
    namespace: vault
  - kind: ServiceAccount
    name: vault-agent-injector
    namespace: vault
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:nonroot'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'system:openshift:scc:hostmount-anyuid'
  namespace: vault
subjects:
  - kind: ServiceAccount
    name: vault
    namespace: vault
  - kind: ServiceAccount
    name: vault-agent-injector
    namespace: vault
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:hostmount-anyuid'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'system:openshift:scc:hostpath'
  namespace: vault
subjects:
  - kind: ServiceAccount
    name: vault
    namespace: vault
  - kind: ServiceAccount
    name: vault-agent-injector
    namespace: vault
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:hostpath'
