apiVersion: v1
kind: Pod
metadata:
  name: fiware-debug-pod
  namespace: fiware
  labels:
    app: fiware-debug-pod
spec:
  containers:
  - image: quay.io/centos/centos:stream8
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    name: fiware-debug-pod
  restartPolicy: Always
