apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: computate-openshift-client-secret
  namespace: openshift-config
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: fiware-cluster-secrets
    kind: ClusterSecretStore
  target:
    name: computate-openshift-client-secret
    namespace: openshift-config
  dataFrom:
    - extract:
        key: fiware/computate-openshift-client-secret
      