apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: computate-openshift-client-secret
  namespace: openshift-config
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  target:
    name: computate-openshift-client-secret
  dataFrom:
    - extract:
        key: openshift-config/kv/computate-openshift-client-secret
      