apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret-store
  namespace: group-sync-operator
spec:
  provider:
    vault:
      server: http://vault.vault.svc.cluster.local:8200
      path: group-sync-operator/kv
      version: v1
      auth:
        kubernetes:
          mountPath: kubernetes/
          role: secret-reader
          serviceAccountRef:
            name: default
