apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sso-openshift-client-secret
  namespace: openshift-config
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: fiware-cluster-secrets
    kind: ClusterSecretStore
  target:
    name: sso-openshift-client-secret
  dataFrom:
    - extract:
        key: fiware/sso-openshift-client-secret
      