apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: pecan-unconstrained-forecast
  namespace: redhat-ods-applications
  labels:
    opendatahub.io/notebook-image: "true"
  annotations:
    opendatahub.io/notebook-image-url: "https://github.com/opendatahub-io-contrib/workbench-images"
    opendatahub.io/notebook-image-name: "PEcAn Unconstrained Forecast"
    opendatahub.io/notebook-image-desc: "Datascience + RStudio JupyterLab Notebook image for PEcAn Ecological Forecasting"
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      annotations: null
      from:
        kind: DockerImage
        name: 'quay.io/computateorg/pecan-unconstrained-forecast:latest'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
