kind: Service
apiVersion: v1
metadata:
  name: zookeeper-nodeport
  namespace: solr
spec:
  ports:
    - name: default-solrcloud-zookeeper-client
      protocol: TCP
      port: 2181
      targetPort: 2181
      nodePort: 30081
  type: NodePort
  selector:
    app: default-solrcloud-zookeeper
