apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: smartcity
  namespace: sso
  labels:
    app: sso
    realm: SMARTCITY
    client: smartcity
spec:
  realmSelector:
     matchLabels:
      app: sso
      realm: SMARTCITY
  client:
    clientId: smartcity
    standardFlowEnabled: true
    serviceAccountsEnabled: true
    authorizationServicesEnabled: true
    frontchannelLogout: true
    protocol: openid-connect
    redirectUris:
      - http://localhost:12080/logout
      - http://localhost:12080/callback
      - https://oauth-openshift.apps-crc.testing/oauth2callback/sso
    defaultClientScopes:
      - profile
      - smartcity
    authorizationSettings:
      scopes:
        - id: POST
          name: POST
          displayName: POST
        - id: DELETE
          name: DELETE
          displayName: DELETE
        - id: GET
          name: GET
          displayName: GET
        - id: PATCH
          name: PATCH
          displayName: PATCH
        - id: PUTImport
          name: PUTImport
          displayName: PUTImport
        - id: Search
          name: Search
          displayName: Search
      resources:
        - name: TrafficSimulation
          displayName: TrafficSimulation
          uris:
            - /api/traffic-simulation
            - /traffic-simulation
          scopes:
            - POST
            - DELETE
            - GET
            - PATCH
            - PUTImport
            - Search
      policies:
        - id: admin
          name: admin
          logic: POSITIVE
          decisionStrategy: UNANIMOUS
          type: role
          config:
            roles: "[{\"id\":\"admin\",\"required\":true}]"
