apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: smartcity
  namespace: sso
  labels:
    app: sso
spec:
  realmSelector:
     matchLabels:
      app: sso
      realm: SMARTCITY
  client:
    clientId: smartcity
    standardFlowEnabled: true
    serviceAccountsEnabled: true
    authorizationServicesEnabled: true
    protocol: openid-connect
    redirectUris:
      - http://localhost:12080/logout
      - http://localhost:12080/callback
      - https://oauth-openshift.apps-crc.testing/oauth2callback/sso
