kind: Kafka
apiVersion: kafka.strimzi.io/v1beta2
metadata:
  name: smartvillage-kafka
  namespace: smart-village-view
spec:
  kafka:
    version: 3.3.1
    replicas: 3
    authorization:
      type: simple
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        tls: true
        type: nodeport
        authentication:
          type: tls
        configuration:
          bootstrap:
            nodePort: 32100
          brokers:
            - broker: 0
              nodePort: 32000
              advertisedHost: kafka0.apps-crc.testing
            - broker: 1
              nodePort: 32001
              advertisedHost: kafka1.apps-crc.testing
            - broker: 2
              nodePort: 32002
              advertisedHost: kafka2.apps-crc.testing
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
