---
REDHAT_OPENSHIFT_HOST: https://api.crc.testing:6443
REDHAT_OPENSHIFT_TOKEN: "{{ lookup('env', 'REDHAT_OPENSHIFT_TOKEN') | default(omit) }}"
POSTGRES_POD_LABEL: postgres-operator.crunchydata.com/data=postgres
POSTGRES_USER_SECRET_PECAN: postgres-cluster-pguser-pecan
POSTGRES_NAMESPACE: postgres
SSO_NAMESPACE: pecan
SSO_POSTGRES_SECRET_NAME: pecan-db-secret
POSTGRES_PORT: 80
# The default path to the PostgreSQL hba file to manage user permissions. 
POSTGRES_HBA_CONF: "/pgdata/pg15/pg_hba.conf"
