apiVersion: redhatcop.redhat.io/v1alpha1
kind: RandomSecret
metadata:
  name: sso-group-sync
  namespace: group-sync-operator
spec:
  authentication: 
    path: kubernetes
    role: secret-writer
  connection:
    address: 'http://vault.vault.svc.cluster.local:8200'
  path: group-sync-operator/kv
  secretKey: password
  secretFormat:
    passwordPolicyName: special-characters-password-policy-15
