---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'system:openshift:scc:anyuid'
  namespace: vault
subjects:
  - kind: ServiceAccount
    name: vault-operator
    namespace: vault
  - kind: ServiceAccount
    name: vault-operator-agent-injector
    namespace: vault
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:anyuid'
