apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: betydb-postgresql
  namespace: pecan
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  target:
    name: betydb-postgresql
    template:
      type: Opaque
      engineVersion: v2
      data:
        postgresql-password: "{{ .postgresqlPassword }}"
  data:
  - secretKey: postgresqlPassword
    remoteRef:
      key: pecan/kv/betydb
      property: postgresqlPassword
