apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: sso
  namespace: sso
  labels:
    app: sso
spec:
  instances: 1
  externalAccess:
    enabled: true
  externalDatabase:
    enabled: true
