---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: site-solrcloud
spec:
  replicas: 2
  selector:
    matchLabels:
      solr-cloud: default
      technology: solr-cloud
  template:
    metadata:
      creationTimestamp: null
      labels:
        solr-cloud: default
        technology: solr-cloud
      annotations:
        solr.apache.org/solrXmlMd5: 843652bc6b529b66f46bcdae6764ab4e
    spec:
      serviceAccountName: solr
      volumes:
        - name: solr-xml
          configMap:
            name: default-solrcloud-configmap
            items:
              - key: solr.xml
                path: solr.xml
            defaultMode: 444
        - name: data
          emptyDir: {}
        - name: computate-configset
          configMap:
            defaultMode: 440
            name: computate-configset
      initContainers:
        - name: cp-solr-xml
          image: 'library/busybox:1.28.0-glibc'
          command:
            - sh
            - '-c'
            - cp /tmp/solr.xml /tmp-config/solr.xml
          resources: {}
          volumeMounts:
            - name: solr-xml
              mountPath: /tmp
            - name: data
              mountPath: /tmp-config
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      containers:
        - resources: {}
          readinessProbe:
            httpGet:
              path: /solr/admin/info/system
              port: 8983
              scheme: HTTP
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          lifecycle:
            preStop:
              exec:
                command:
                  - solr
                  - stop
                  - '-p'
                  - '8983'
          name: solrcloud-node
          livenessProbe:
            httpGet:
              path: /solr/admin/info/system
              port: 8983
              scheme: HTTP
            initialDelaySeconds: 20
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: SOLR_JAVA_MEM
              value: '-Xms1g -Xmx2g'
            - name: SOLR_HOME
              value: /var/solr/data
            - name: SOLR_PORT
              value: '8983'
            - name: SOLR_NODE_PORT
              value: '8983'
            - name: POD_HOSTNAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: SOLR_HOST
              value: $(POD_HOSTNAME).default-solrcloud-headless.solr
            - name: SOLR_LOG_LEVEL
              value: INFO
            - name: GC_TUNE
            - name: SOLR_STOP_WAIT
              value: '55'
            - name: ZK_HOST
              value: >-
                default-solrcloud-zookeeper-0.default-solrcloud-zookeeper-headless.solr.svc.cluster.local:2181,default-solrcloud-zookeeper-1.default-solrcloud-zookeeper-headless.solr.svc.cluster.local:2181,default-solrcloud-zookeeper-2.default-solrcloud-zookeeper-headless.solr.svc.cluster.local:2181/
            - name: ZK_CHROOT
              value: /
            - name: ZK_SERVER
              value: >-
                default-solrcloud-zookeeper-0.default-solrcloud-zookeeper-headless.solr.svc.cluster.local:2181,default-solrcloud-zookeeper-1.default-solrcloud-zookeeper-headless.solr.svc.cluster.local:2181,default-solrcloud-zookeeper-2.default-solrcloud-zookeeper-headless.solr.svc.cluster.local:2181
            - name: SOLR_OPTS
              value: '-DhostPort=$(SOLR_NODE_PORT)'
          ports:
            - name: solr-client
              containerPort: 8983
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: data
              mountPath: /var/solr/data
            - mountPath: "/opt/solr/server/solr/configsets/computate/conf"
              name: computate-configset
          terminationMessagePolicy: File
          image: 'library/solr:8.1.1'
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      dnsPolicy: ClusterFirst
      securityContext:
        fsGroup: 8983
      schedulerName: default-scheduler
  serviceName: default-solrcloud-headless
  podManagementPolicy: Parallel
  updateStrategy:
    type: OnDelete
  revisionHistoryLimit: 10
