apiVersion: redhatcop.redhat.io/v1alpha1
kind: PasswordPolicy
metadata:
  name: special-characters-password-policy-15
  namespace: vault-admin
spec:
  # Add fields here
  authentication: 
    path: kubernetes
    role: policy-admin
  connection:
    address: 'http://vault.vault.svc.cluster.local:8200'
  passwordPolicy: |
    length = 15
    rule "charset" {
      charset = "abcdefghjkmnpqrstuvwxyz"
      min-chars = 1
    }
    rule "charset" {
      charset = "ABCDEFGHJKMNPQRSTUVWXYZ"
      min-chars = 1
    }
    rule "charset" {
      charset = "23456789"
      min-chars = 1
    }
    rule "charset" {
      charset = "!@#$%-_"
      min-chars = 1
    }
