---
apiVersion: image.openshift.io/v1
kind: ImageStream
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      annotations: null
      from:
        kind: DockerImage
        name: 'quay.io/computate/smart-village-view:latest'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
