kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: smartvillage-traffic-light-controller-sumo
  namespace: smart-village-view
spec:
  lookupPolicy:
    local: false
  tags:
    - name: computate-api
      from:
        kind: DockerImage
        name: 'quay.io/computateorg/smartvillage-traffic-light-controller-sumo:computate-api'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
