apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/
  - namespaces/
patchesStrategicMerge:
  - applications/betydb-helm/application.yaml
  - applications/pecan-helm/application.yaml
