---
pageId: "openapi-specification"
uri: "/en-us/{{ pageId }}"
url: "{{ page.siteBaseUrl }}{{ uri }}"
h1: What APIs are used in {{ page.siteDisplayName }}? 
h2: Discover the OpenAPI 3 specification for the project
created: "2022-05-27"
courseNum: 1
lessonNum: 5
author:
  name: Christopher Tate
  title: Red Hat Principal Software Consultant
pageImageUri: "/png/{{ pageId }}/infographic.png"
htmTitle:
  - text: "{{ h1 }}{{ h2 }}"
htmMeta:
  - {e: meta, a: {property: "og:title", content: "{{ h1 }}"}}
  - {e: meta, a: {property: "og:description", content: "{{ h2 }}"}}
  - {e: meta, a: {property: "og:url", content: "{{ page.siteBaseUrl }}{{ uri }}"}}
  - {e: meta, a: {property: "og:site_name", content: "{{ page.siteName }}"}}
  - {e: meta, a: {property: "og:image", content: "{{ page.staticBaseUrl }}{{ pageImageUri }}"}}
  - comment: |
      install -d {{ page.staticPath }}/png/{{ pageId }}/
      CutyCapt --min-height=1 --url='{{ page.siteBaseUrl }}{{ uri }}?var=filterLabel:infographic' --out='{{ page.staticPath }}/png/{{ pageId }}/infographic.png'
      CutyCapt --min-height=1 --url='{{ page.siteBaseUrl }}{{ uri }}?var=filterLabel:review' --out='{{ page.staticPath }}/png/{{ pageId }}/review.png'
      CutyCapt --min-height=1 --url='{{ page.siteBaseUrl }}{{ uri }}?var=filterLabel:image' --out='{{ page.staticPath }}/png/{{ pageId }}/image.png'
      
  - {e: meta, a: {property: "og:image:width", content: "{{ page.pageImageWidth }}"}}
  - {e: meta, a: {property: "og:image:height", content: "{{ page.pageImageHeight }}"}}
  - {e: meta, a: {property: "og:image:type", content: "{{ page.pageImageType }}"}}
  - {e: meta, a: {property: "og:image:alt", content: "{{ h1 }} {{ h2 }}"}}
  - {e: meta, a: {property: "og:type", content: "article"}}
  - {e: meta, a: {property: "twitter:card", content: "summary_large_image"}}
  - {e: meta, a: {property: "twitter:title", content: "{{ h1 }}"}}
  - {e: meta, a: {property: "twitter:description", content: "{{ h2 }}"}}
  - {e: meta, a: {property: "twitter:image", content: "{{ page.staticBaseUrl }}{{ pageImageUri }}"}}
  - {e: meta, a: {property: "description", content: "{{ h2 }}"}}
htmBody:
- e: div
  a:
    class: w3-card w3-padding w3-margin-top w3-show w3-white 
  in:
  - e: div
    a:
      class: w3-padding
    in:
      - e: h1
        a:
          class: w3-text-2017-shaded-spruce 
        in:
          - e: i
            a:
              class: fa-light fa-compact-disc padding-right-quarter-em
          - e: span
            text: "{{ h1 }}"
      - e: h2
        a:
          class: w3-text-2017-shaded-spruce 
        in:
          - e: i
            a:
              class: fa-brands fa-redhat padding-right-quarter-em
          - e: span
            text: "{{ h2 }}"
      - e: div
        a:
          class: font-style-italic 
        text: 'Created {{formatZonedDateTime created "EEE MMM d yyyy" "en-US" "America/Denver" }}'
      - e: p
        in:
          - e: div
            a:
              class: font-weight-bold 
            text: "By {{ author.name }}"
          - e: div
            a:
              class: font-weight-bold font-style-italic
            in:
              - e: i
                a:
                  class: fa-brands fa-redhat w3-text-red
              - e: span
                a:
                  class: font-weight-bold 
                text: "{{ author.title }}"
      - e: div
        a:
          class: w3-row w3-mobile 
        label: 
          - infographic
          - image
        in:
      - e: div
        a:
          class: w3-row w3-mobile 
        label: 
          - infographic
          - image
        in:
          - e: img
            a:
              class: w3-image 
              src: "{{ page.staticBaseUrl }}/png/{{ pageId }}/image.png"
  - e: div
    in:
      - e: div
        a:
          class: w3-padding 
        in:
          - e: h3
            a:
              class: w3-text-2017-shaded-spruce 
            in:
              - e: i
                a:
                  class: fa-regular fa-microchip padding-right-quarter-em
              - e: span
                text: What can your web application do? 
          - e: h4
            a:
              class: w3-text-2017-shaded-spruce 
            in:
              - e: i
                a:
                  class: fa-regular fa-list-tree padding-right-quarter-em
              - e: span
                text: Review the OpenAPI specification
          - e: p
            text: |-
              Here is a link to the OpenAPI specification for {{ page.siteDisplayName }}: 
          - e: a
            a:
              target: _new
              href: https://studio-ws.apicur.io/sharing/bcd69fc4-cc10-40c1-bb40-03ddfe5cf050
            text: https://studio-ws.apicur.io/sharing/bcd69fc4-cc10-40c1-bb40-03ddfe5cf050
  - e: div
    label:
      - infographic
      - review
    a:
      id: divReview
    in:
      - e: table
        a:
          id: tableReview1
          class: review1Table 
        in:
          - e: tbody
            in:
              - e: tr
                a:
                  class: 
                in:
                  - e: td
                    a:
                      class: w3-mobile review1TableTr1Td1 review1TableTr1Td even 
                    in:
                      - e: span
                        text: '{{formatZonedDateTime created "EEEE" "en-US" "America/Denver" }}'
                  - e: td
                    a:
                      class: w3-mobile review1TableTr1Td2 review1TableTr1Td odd 
                    in:
                      - e: i
                        a:
                          class: "{{ htmBody.0.in.0.in.0.in.0.a.class }}"
                  - e: td
                    a:
                      class: w3-mobile review1TableTr1Td3 review1TableTr1Td even 
                    in:
                      - e: i
                        a:
                          class: "{{ htmBody.0.in.0.in.1.in.0.a.class }}"
                  - e: td
                    a:
                      class: w3-mobile review1TableTr1Td4 review1TableTr1Td odd 
                    in:
                      - e: i
                        a:
                          class: "fa-solid fa-pen-nib"
              - e: tr
                a:
                  class: odd 
                in:
                  - e: td
                    a:
                      class: w3-mobile review1TableTr2Td1 review1TableTr2Td even 
                    in:
                      - e: span
                        text: '{{formatZonedDateTime created "MMMM d yyyy" "en-US" "America/Denver" }}'
                  - e: td
                    a:
                      class: w3-mobile review1TableTr2Td2 review1TableTr2Td odd 
                    in:
                      - e: span
                        text: "{{ h1 }}"
                  - e: td
                    a:
                      class: w3-mobile review1TableTr2Td3 review1TableTr2Td even 
                    in:
                      - e: span
                        text: "{{ h2 }}"
                  - e: td
                    a:
                      class: w3-mobile review1TableTr2Td4 review1TableTr2Td odd 
                    in:
                      - e: span
                        text: "{{ author.name }}"
      - e: table
        a:
          id: tableReview2
          class: review2Table 
        in:
          - e: tbody
            each: htmBody.0.in.1.in
            in:
              - e: tr
                a:
                  class: "{{#even @index }}review2TableTr even {{else}}review2TableTr odd {{/even}}"
                in:
                  - e: td
                    a:
                      class: w3-mobile 
                    in:
                      - e: i
                        a:
                          class: "{{ item.in.0.in.0.a.class }}"
                      - e: span
                        text: '{{ item.in.0.in.1.text }}'
                  - e: td
                    a:
                      class: w3-mobile 
                    in:
                      - e: i
                        a:
                          class: "{{ item.in.1.in.0.a.class }}"
                      - e: span
                        text: '{{ item.in.1.in.1.text }}'
