apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sso-group-sync
  namespace: group-sync-operator
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: fiware-cluster-secrets
    kind: ClusterSecretStore
  target:
    name: sso-group-sync
  dataFrom:
    - extract:
        key: fiware/sso-group-sync
      