apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sso-group-sync
  namespace: group-sync-operator
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  target:
    name: sso-group-sync
    template:
      type: Opaque
      engineVersion: v2
      data:
        username: "group-sync"
        password: "{{ .password }}"
  data:
  - secretKey: password
    remoteRef:
      key: group-sync-operator/kv/sso-group-sync
      property: password
