apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
  name: pecan-helm
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/computate-org/pecan-helm.git
    targetRevision: HEAD
    path: .
    helm:
      releaseName: pecan
      parameters:
        - name: betydb.enabled
          value: "false"
        - name: betydb.postgresql.enabled
          value: "false"
#        - name: betydb.postgresql.postgresqlHost
#          value: "postgres-cluster-ha.postgres.svc.cluster.local"
        - name: betydb.postgresql.postgresqlHost
          value: "pecan-postgresql.pecan.svc.cluster.local"
        - name: betydb.postgresql.postgresqlUser
          value: "postgres"
        - name: betydb.postgresql.postgresqlUsername
          value: "postgres"
        - name: betydb.postgresql.postgresqlDatabase
          value: "postgres"
        - name: betydb.postgresql.service.port
          value: "5432"
        - name: betydb.service.port
          value: "8000"

        - name: clustername
          value: "pecan-server"
        - name: clusterfqdn
          value: "pecan-server-pecan.apps-crc.testing"
        - name: initializeData
          value: "true"
        - name: ingress.enabled
          value: "true"
        - name: "pecan.env.betydb"
          value: "http://betydb.pecan.svc.cluster.local:8000/"
        - name: "betydb.betyUser"
          value: "bety"
        - name: "betydb.betyDatabase"
          value: "bety"
        - name: "betydb.ingress.hosts"
          value: "{betydb.pecan.svc.cluster.local}"
        - name: "ingress.hosts"
          value: "{pecan-server-pecan.apps-crc.testing}"
  destination:
    namespace: pecan
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      # resources that no longer exist get deleted on sync
      prune: true
      # sync will be attempted again on failure after self heal timeout (5 seconds by default)
      selfHeal: true
